Add SilverStripe 4 support (Fixes #5)
robingram/silverstripe-unused-file-report pull request #6
Opened 2018-12-09 21:09 UTC by wilr

Test Task, Report view and update classes.

Move to correct namespace (robingram) as SilverStripe is limited to SilverStripe Org.

Add ability to filter files by title.

2018-12-11 22:18 UTC, robingram commented
Nice @wilr. Looks like you've cleaned up a lot of my crap. ;)

I'm a little pushed for time right now for a full review but I'll try to get it done by the weekend.

2018-12-13 20:49 UTC, robingram requested changes
@wilr This looks great. I did the original in a bit of a rush so you've fixed it up nicely.

I fixed the `composer.json` in `master` so that I could cut a full release and set up a SS3 maintenance branch so if you could rebase I'll get this merged in and cut a 2.x release.

2018-12-13 21:01 UTC, wilr commented
Rebased on master

2018-12-14 01:02 UTC, robingram approved these changes

2018-12-14 01:03 UTC, merged